pipeline:
  test:
    image: alpine
    commands:
      - env | sort

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]

matrix:
  TEST_VAR:
    - one
    - two
    - three
